name: Deploy PR Preview
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm ci
          npm run build        # собирает ./dist

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist
          target-branch: gh-pages
